/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmad
 */
public class frame2 extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    public frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "value1", "value2", "value3", "value4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from books_borrowed";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String TransactionID=rs.getString("title");
                    String MemberID=rs.getString("borrowed_date");
                    String AmountPaid=rs.getString("due_date");
                    String DateOfPayment=rs.getString("returned_date");
                    String tbData[]={TransactionID,MemberID,AmountPaid,DateOfPayment};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from particular_city";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String TransactionID=rs.getString("title");
                    String MemberID=rs.getString("name");
                    String AmountPaid=rs.getString("due_date");
                    String DateOfPayment=rs.getString("returned_date");
                    String tbData[]={TransactionID,MemberID,AmountPaid,DateOfPayment};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from all_members";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String TransactionID=rs.getString("name");
                    String MemberID=rs.getString("email");
                    String AmountPaid=rs.getString("borrowed_date");
                    String DateOfPayment=rs.getString("due_date");
                    String tbData[]={TransactionID,MemberID,AmountPaid,DateOfPayment};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from particular_publisher";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String TransactionID=rs.getString("publisher");
                    String MemberID=rs.getString("title");
                    String AmountPaid=rs.getString("author");
                    String DateOfPayment=rs.getString("isbn");
                    String tbData[]={TransactionID,MemberID,AmountPaid,DateOfPayment};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from borrower_phone";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String TransactionID=rs.getString("name");
                    String MemberID=rs.getString("title");
                    String AmountPaid=rs.getString("author");
                    String DateOfPayment=rs.getString("isbn");
                    String tbData[]={TransactionID,MemberID,AmountPaid,DateOfPayment};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from all_fine";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String TransactionID=rs.getString("total_fine");
                    String tbData[]={TransactionID};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from overdue";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                   String TransactionID=rs.getString("title");
                    String MemberID=rs.getString("borrowed_date");
                    String AmountPaid=rs.getString("due_date");
                    String tbData[]={TransactionID,MemberID,AmountPaid};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from borrowed_more";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                   String TransactionID=rs.getString("title");
                    String MemberID=rs.getString("times_borrowed");
                    String tbData[]={TransactionID,MemberID};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
             try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from author_english_langauage";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                   String TransactionID=rs.getString("title");
                    String MemberID=rs.getString("author");
                    String tbData[]={TransactionID,MemberID};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
               try{
               Class.forName("oracle.jdbc.driver.OracleDriver");

    // Step 2: Create a connection
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String username = "sys as sysdba";
    String password = "orcl";
    Connection conn = DriverManager.getConnection(url, username, password);
    // Step 3: Create a statement
    Statement stmt = conn.createStatement();
    // Step 4: Execute a query
    String sql="select * from specific_author";
    ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                   String TransactionID=rs.getString("name");
                    String tbData[]={TransactionID};
                    DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
                }
            rs.close();
    stmt.close();
    conn.close();

        }
        catch(ClassNotFoundException | SQLException e){  System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
